### ISSUE TITLE
Simple Echo example

### ISSUE THREAD

**Issue by jaguardo** [flynneva/react-ros#12]
Trying to follow the example here:
https://flynneva.github.io/react-ros/examples/simple_echo/

get an error on 
```
{topics.map((topic, i) => <li key={i}>    {topic.path}</li>)}
````
TypeError: Cannot read property 'map' of undefined.

additionally, can't find where EchoTopic is defined to be able to use:
```
<ROS>
  <ToggleConnect />
  <EchoTopic />
</ROS>
```

only ToggleConnect is defined in the example... is there another part of the example?

**Comment by jaguardo** [comment]
I see now the extra EchoTopic.js in the example folder.  Could probably add that piece of info to the example page, wasn't exactly clear.

**Comment by flynneva** [comment]
@jaguardo awesome to hear you found what you were looking for. I'll add that bit of code to the docs as you requested. Give me some time to update it!

**Comment by flynneva** [comment]
updated docs with #11. closing this issue for now...thanks for the feedback!
