### ISSUE TITLE
Enhancement - be able to add properties to (or before) function call to useROS()

### ISSUE THREAD

**Issue by jaguardo** [flynneva/react-ros#16]
Probably a few ways to skin the cat (and admittedly I might be missing the subtle context to do this already), but for example - to display a different url/default url immediately with page loading, from the example I tried to modify with this in the ToggleConnect():
```
  const { isConnected, topics, url, changeUrl, toggleConnection } = useROS();
  const defaultURL = "ws://xxx.xxx.xxx.xx:9090"
  changeUrl(defaultURL);
```

however, this gets called a million times and throws an error... workaround is to add an if statement
```
  const defaultURL = "ws://xxx.xxx.xxx.xx:9090"
  if (url !== defaultURL){
  changeUrl(defaultURL);
}
```

better would be to add it as a parameter (or a list of parameters to pass) with the function call? (new to React, not sure if that is possible?)

**Comment by flynneva** [comment]
the ToggleConnect component is just an example of one way to use this package.

i think what you are looking for here is already available in react by using the `useEffect` hook.

something like this should do what you want i think:
```
import React, { useEffect } from 'react'
import { useROS } from '../ROS'

function ToggleConnect() {
  const { isConnected, topics, url, changeUrl, toggleConnection } = useROS();

  const defaultURL = "ws://xxx.xxx.xxx.xxx:9090"

  // this runs every render
  useEffect(() => {
    let mounted = true
    if (mounted) {
      if (url != defaultURL) {
        changeUrl(defaultURL)
      }
      return () => mounted = false
    }
  })

  return (
```

**Comment by jaguardo** [comment]
copy, I think this will work too:
```
  useEffect(() => {
  if (url !== defaultURL) {
    changeUrl(defaultURL);
  }
  },[])
  ```
  However I'm not exactly always getting what I want, let's say I want to set the option "autoconnect" is there a way to do that before useROS()?  It is checked 
  ```
    React.useEffect(function () {
    if (!ros.isConnected) {
      if (ros.autoconnect) {
        console.log('autoconnecting');
      }
    }
  });
```

I'd like to set it before if possible.

**Comment by flynneva** [comment]
good point. it looks like i added in that `ros.autoconnect` context prop without actually allowing anyone to set it 😄 really useful, huh?

ill see if I can modify the code a bit so you can do this for `autoconnect`...and maybe a few others.

any other missing context features that you see please let me know

**Comment by jaguardo** [comment]
I'm learning as I go!  I haven't quite figured out the react way of thinking yet...

**Comment by flynneva** [comment]
I think this was my first react package that used `useEffect` and `useContext`....and even might've been my first react package actually 🤔  so I am definitely learning as I go as well

**Comment by flynneva** [comment]
@jaguardo  i just pushed an update that should enable you to use the `autoconnect` state. ive added an example on how to do this using the [`ToggleConnect` component here](https://github.com/flynneva/react-ros/blob/b2967b898c5edacde97dce2f805d81ab5360b9df/src/components/examples/ToggleConnect.js#L17).

when the component is first mounted it will do a quick check then change autoconnect to `true`. once changed, that will trigger a re-render and the new ROS.js context should now automaticaly connect to whatever URL/port was set previously. im sure this probably has some down-sides.....but it should kind of do what you're looking for i think. for now lets try it out for awhile until someone complains about it and go from there.

**Comment by flynneva** [comment]
feel free to close this if you're satisfied with the change

**Comment by jaguardo** [comment]
I was trying it out, when I ran across another interesting item... I'll create a new issu.e

**Comment by jaguardo** [comment]
Seems to work well... the only additional input I'd have, that may or may not make sense depending on the project setup, is (using the simple example/demo), I would "autodisconnect" as well when the url changes... or allow another state that shows the current url that you are still connected to.

because if you change the url in the input box and it subsequently changes the ros url, but you are still connected to another url? I believe you have no way to know what that url (the one you are connected to) was.

**Comment by flynneva** [comment]
good tip! ill go ahead and add that in there
