### ISSUE TITLE
Enhancement- Add the ability to read/use ROS Bags.

### ISSUE THREAD

**Issue by jaguardo** [flynneva/react-ros#17]
Perhaps leveraging the rosbag module: 
https://developer.aliyun.com/mirror/npm/package/rosbag

**Comment by flynneva** [comment]
so this is a good suggestion for anyone who is making a website that plays back rosbags, but might be out of scope for this package. introducing this here might make this package unnecessarily big/complex if someone just simply wants to visualize their ROS camera on their website or something i think.

**Comment by jaguardo** [comment]
fair enough
