### ISSUE TITLE
Can't access ROS state from other levels (child)

### ISSUE THREAD

**Issue by jaguardo** [flynneva/react-ros#18]
Might be my mis-understanding of useContext and global-ish variables... but I would have thought this would have worked to update state values for both instances of ToggleConnect and EchoTopic.

From the basic/standard create react app, i.e. ```yarn create react-app my-app```, I put 2 calls to ToggleConnect and EchoTopic, one in Index.js under a <ROS> tag and one in App.js that should still fall under the <ROS> tag in Index.js (regardless I tried adding an additional <ROS> tag in App.js with no change.

index.js
```ReactDOM.render(
  <React.StrictMode>
    <ROS>
    <App />
    <ToggleConnect />
    <EchoTopic />
    </ROS>
  </React.StrictMode>,
  document.getElementById('root')
);
```

App.js
```
function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
        
      <ToggleConnect />
      <EchoTopic />
    
      </header>
    </div>
  );
}
```

I would have thought the outputs of each ToggleConnect and EchoTopic call would be the same, but they're not, they don't update each other... so I assume each is a separate set of States?

in contrast, this works:
```
ReactDOM.render(
  <React.StrictMode>
    <ROS>
    <App />
      <ToggleConnect />
      <EchoTopic />
      <ToggleConnect />
      <EchoTopic />
    </ROS>
  </React.StrictMode>,
  document.getElementById('root')
);
```

what is done in one effects and updates the other.

I would like to create a status button or light of some sort in another section of my site, but I can't get it to update correctly (doesn't pull in the correct state information)

**Comment by jaguardo** [comment]
Might be a browser thing, I can't get it to repeat now... works as I originally thought!

**Comment by flynneva** [comment]
if you'd like to see a working example of it I tried to get it semi-working in the docs but also i use it on my personal website [flynnlabs.dev](https://flynnlabs.dev/robotics). you can test it out for yourself and get some ideas from the source code by heading over to [it on github](https://github.com/flynneva/flynn-labs.git)

**Comment by flynneva** [comment]
going to close this now if its no longer an issue
