### ISSUE TITLE
Real-time access to roslibjs.

### ISSUE THREAD

**Issue by jaguardo** [flynneva/react-ros#40]
Not sure the best way to attack this... but I need to have to pretty quick recognition of connection status and message disruption.

After ros.isConnected is set, there is really nothing "checking" that ros.ROS.isConnected is still true, so it is possible for the latter to go false while the former stays true.  Additionally the later does not go true as quickly as the former, so there is a mismatch between the 2.  ros.isConnected goes true, then a few epochs later ros.ROS.isConnected goes true, so its not enough to put an Effect to look for the later to go false, since it is not truly linked to the other.

been thinking about a usetimer effect or something to continuously look at the roslibjs status.  Perhaps as an option to set within react-ros?

**Comment by jaguardo** [comment]
Threw together a "checkConnection" function and another variable (ROSConfirmedConnected, could use a better name)... upto the user to come up with their own way to integrate it (https://github.com/jaguardo/react-ros/commit/ef866b67ae09efa2fcbbc668674b9b110593a63e)
```
  function checkConnection() {
    if (ros.ROS){
      if (ros.isConnected) {
        if (!ros.ROSConfirmedConnected && ros.ROS.isConnected) {
          setROS(ros => ({ ...ros, ROSConfirmedConnected: ros.ROS.isConnected }))
          console.log("Both react-ros and roslibjs have confirmed connection.")
        }
        // Once we have that "confirmation"  we need to continously check for good connection
        else if (ros.ROSConfirmedConnected && !ros.ROS.isConnected) {
          setROS(ros => ({ ...ros, isConnected: false }));
          handleDisconnect();
        }
        else if (!ros.ROS.isConnected) {
          console.log("React-ros has confirmed the connection, roslibjs has not yet.")
        }
      }
    }
    else{
      console.log("Initial connection not established yet")
    }
  }
```

not sure what your big picture philosophy is... can add a PR if you want it, or can iterate on it some.

**Comment by flynneva** [comment]
@jaguardo  same here, can we close this?
